# Generated by Django 5.2.8 on 2025-12-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_add_profile_fields'),
    ]

    operations = [
    ]
